name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          NEW_VERSION: ${{ env.VERSION }}
        run: |
          echo "Starting login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "New version: $NEW_VERSION"
          echo "End login"

      - name: Build Docker Image
        env:
          NEW_VERSION: ${{ env.VERSION }}
        run: |
          docker build -t freddyarh/fredy-website:$NEW_VERSION .
          docker build -t freddyarh/fredy-website:latest .

      - name: Push Docker Image
        env:
          NEW_VERSION: ${{ env.VERSION }}
        run: |
          docker push freddyarh/fredy-website:$NEW_VERSION
          docker push freddyarh/fredy-website:latest
